name: OCaml CI

on:
  push:
  pull_request:
    types: [synchronize]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-test:

    strategy:
      matrix:
        ocaml-version:
          - 4.14.1
          - 5.0.0
        node-version:
          - hydrogen # v18 Active LTS
          - latest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2

      - name: Build and test
        id: camlbuild
        uses: kxcdev/ocaml-general-gha@v3
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          node-version: ${{ matrix.node-version }}
          pr-report-test-result: ${{ matrix.node-version == 'latest' }}

  odoc-github-pages:

    needs: build-test

    ## FIXME: ci-improvements => main
    if: ${{ github.repository == 'anzaux/opstic' && github.event_name == 'push' && github.ref == 'refs/heads/ci-improvements' }}

    environment:
      name: github-pages

      ## waiting for resolution of actions/runner#2009
      #url: ${{ steps.camlbuild.outputs.odoc-github-pages-url }}
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2

      - name: Build and test
        id: camlbuild
        uses: kxcdev/ocaml-general-gha@v3
        with:
          skip-testing: true
          report-test-result: false

          with-odoc: true
          odoc-build-command: |
            echo vendors/kxclib vendors/prr vendors/rows . | xargs -n1 \
              opam exec -- dune build @doc-private @doc --build-dir="$(pwd)/_build" --root
          odoc-upload-artifact: true
          odoc-upload-artifact-name: "github-pages"

          ## waiting for resolution of actions/runner#2009
          # odoc-deploy-github-pages: true

      - name: Setup Pages
        if: ${{ inputs.odoc-deploy-github-pages }}
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
